#!/bin/bash

set -x

# Get DB details
juju-log "Getting database connection details"
 
database=`relation-get database`
if [ -z "${database}" ]; then
    juju-log "No Database!"
    exit 0
fi
 
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`
database=`relation-get database`
dbport=`relation-get port`
sqlfile=/opt/jboss-as-7.2.0.Final/sql/import-postgres.sql

# Postgres configuration
export PGPASSWORD=$password


juju-log "user $user password $password host $host database $database"


        juju-log "Configure Jboss DS"

        sed -i "s/localhost:5432\/opencell_db/$host:$dbport\/$database/" /opt/jboss-as-7.2.0.Final/standalone/configuration/standalone.xml
        sed -i "s/opencell_db_user/$user/" /opt/jboss-as-7.2.0.Final/standalone/configuration/standalone.xml
        sed -i "s/opencell_db_password/$password/" /opt/jboss-as-7.2.0.Final/standalone/configuration/standalone.xml

        juju-log "Database connexion to Jboss is configured"




juju-log "Checking to see if the DB has been created and populated"

if psql --dbname=$database --username=$user --host=$host -c "SELECT count(*) FROM adm_user"; then
        # Update config settings
        juju-log "Database already populated"
else
	juju-log "Database not populated, importing schema and updating config file"
	juju-log "Create Opencell Database"	


#user='opencell'
#password=`pwgen -s -y -1 14 1`
#database="opencell"

	#psql --dbname=$database --username=$user --host=$host -c "CREATE USER opencell WITH SUPERUSER PASSWORD '$password';"
	#createdb --username=$user --host=$host -O $user $database

	juju-log "Import initials data in Opencell Database"
        
	psql --dbname=$database --username=$user --host=$host < $sqlfile

	juju-log "Opencell Database created and initialized"	

fi



juju-log "Stopping services"
 
hooks/stop
 
juju-log "Starting services"
 
hooks/start

status-set active
open-port 8080


exit 0
